### ISSUE TITLE
Cannot install nextfire; as it cannot parse n

### ISSUE THREAD

**Issue by brewhubomg** [NextFire/homebrew-tap#2]

**Comment by NextFire** [comment]
Which command?

**Comment by jemart64** [comment]
I get the same issue when doing `brew install nextfire/tap/<formula>` and `brew install <formula>`

**Comment by NextFire** [comment]
well you have to replace `<formula>` with the name of the formula you want to install

**Comment by jemart64** [comment]
> well you have to replace `<formula>` with the name of the formula you want to install

Thank you!
